name: rag-demo
channels: [conda-forge, pytorch, defaults]
dependencies:
  - python=3.11
  - pip
  - cassandra-driver=3.29.*         # Cassandra 5-compatible
  # Jupyter (optional, keep if you use notebooks)
  - nbformat
  - nbconvert
  # Git ops
  - gitpython
  # Core ML / NLP
  - transformers>=4.41
  - sentence-transformers>=2.3.0    # must match your embedding dim choice
  - pytorch=2.3.*                   # CPU build by default
  - pydantic=2.7.1
  - requests>=2.28.0
  - python-dotenv>=1.0.0
  - networkx>=3.2                   # GraphRAG viz/debug
  - libgcc-ng
  - prometheus_client>=0.20
  - pip:
      - vllm>=0.4.3
      # ---- GraphRAG + LangChain + CassIO (Cassandra) ----
      - cassio>=0.1.6
      - langchain>=0.2.10
      - langchain-community>=0.2.10
      - langchain-graph-retriever>=0.2.0
      - graph-retriever>=0.2.0
      - langchain-huggingface>=0.1.0   # or rely on langchain_community.embeddings

      # ---- LlamaIndex (still used for building/chunking summaries) ----
      - llama-index-core>=0.10.0
      - llama-index-llms-openai>=0.1.0
      - llama-index-readers-github>=0.1.3
      # Code splitting helpers
      - tree_sitter>=0.20.1
      - tree_sitter_language_pack
      - pyyaml>=6.0
      - rich>=13.0
