name: worker
channels:
  - pytorch        # add this
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - cassandra-driver=3.29.*          # Cassandra 5 + VECTOR support
  - pytorch=2.3.*                    # CPU build; swap to CUDA if you need GPU
  # (optional) notebooks
  - nbformat
  - nbconvert
  # utils
  - gitpython
  - networkx>=3.2
  - pydantic>=2.7
  - requests>=2.28
  - python-dotenv>=1.0.0
  - prometheus_client>=0.20
  - libgcc-ng
  - pip:
      # --- Cassandra + LangChain + GraphRAG ---
      - cassio>=0.1.6
      - langchain>=0.2.10
      - langchain-community>=0.2.10
      - langgraph>=0.2.15
      - langchain-graph-retriever>=0.2.0
      - graph-retriever>=0.2.0
      - langchain-huggingface>=0.1.0

      # --- Embeddings (keeps your 384-dim e5-small-v2) ---
      - transformers>=4.41
      - sentence-transformers>=2.3.0   # for intfloat/e5-small-v2
      # If you later switch to INSTRUCTOR models, also add:
      # - InstructorEmbedding>=1.0.1

      # --- LlamaIndex for ingestion/chunking (not used at query-time) ---
      - llama-index-core>=0.10.0
      - llama-index-readers-github>=0.1.3
      - llama-index-embeddings-huggingface>=0.1.0

      # --- Queue + Redis + metrics ---
      - arq>=0.25.0
      - redis>=5.0.0

      # --- Optional local serving ---
      - vllm>=0.4.3

      # --- Code splitting helpers ---
      - tree_sitter>=0.20.1
      - tree_sitter_language_pack

      # --- QoL ---
      - pyyaml>=6.0
      - rich>=13.0