name: rag-api
channels: [conda-forge, defaults, pytorch]
dependencies:
  - psutil
  - python=3.11
  - pip
  # API dependencies
  - fastapi>=0.111.0
  - uvicorn>=0.29.0
  - redis-py>=5.0
  - starlette>=0.38
  # Common Python packages
  - pydantic>=2.7.1
  - requests>=2.28.0
  - pip:
      - fastapi-health>=0.4.0
      - cassandra-driver>=3.29
      # Packages not available in conda-forge
      - fastapi-health>=0.4.0
      - arq>=0.25.0      # async job queue (uses redis)