name: worker
channels:
  - pytorch        # add this
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - uvicorn>=0.30
  - pydantic>=2.7
  - httpx>=0.27
  - requests>=2.32
  - redis-py>=5.0
  - pytorch>=2.3    # conda package
  - prometheus_client>=0.20
  - pip:
      - uvloop>=0.19; platform_system != "Windows"
      - arq>=0.25.0
      - llama-index>=0.11.0
      - llama-index-vector-stores-cassandra>=0.2.2
      - llama-index-embeddings-huggingface>=0.2.0
      - cassandra-driver>=3.29
      - transformers>=4.42
      - sentence-transformers>=3.0
      - numpy>=1.26
      - python-dotenv>=1.0
