apiVersion: v1
kind: Service
metadata:
  name: cassandra                # DNS:  cassandra.<namespace>.svc.cluster.local
  labels:
    {{- include "rag-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP                # the K-8s default; load-balances to all pods
  ports:
    - name: cql
      port: 9042                 # service port clients use
      targetPort: 9042           # containerPort in StatefulSet
      protocol: TCP
  selector:                      # the same labels the StatefulSet uses
    app: cassandra