apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-github-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  GITHUB_USER: {{ .Values.github.user | quote }}
