apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-repos
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ingest
          image: ghcr.io/yourname/rag-ingest:latest  # build from /scripts
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: token
          command: ["python", "-m", "scripts.ingest_repo"]