apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-repos
spec:
  template:
    spec:
      restartPolicy: Never
      ## --- wait here -----------------------------------------------------
      initContainers:
        - name: wait-for-cassandra
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "⏳ waiting for Cassandra ..."
              max_attempts=30
              attempt=0
              # Create a simple netcat check for basic connectivity
              while [ $attempt -lt $max_attempts ]; do
                if nc -z -w 5 {{ printf "%s-cassandra" .Release.Name }} 9042; then
                  echo "✅ Cassandra port is reachable. Checking service readiness..."
                  # Additional 10 seconds wait for Cassandra to fully initialize after port is available
                  sleep 10
                  echo "✅ Cassandra should be ready now"
                  exit 0
                fi
                attempt=$((attempt+1))
                echo "Attempt $attempt of $max_attempts. Waiting for Cassandra to be ready..."
                sleep 10
              done
              echo "❌ Cassandra failed to become ready within the timeout period"
              exit 1
      ## -------------------------------------------------------------------

      containers:
        - name: ingest
          image: "{{ .Values.ingestjob.image }}"
          imagePullPolicy: {{ .Values.ingestjob.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: CASSANDRA_HOST
              value: "{{ .Release.Name }}-cassandra"
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_USERNAME
              value: "{{ .Values.cassandra.auth.username }}"
            - name: CASSANDRA_PASSWORD
              value: "{{ .Values.cassandra.auth.password }}"
            - name: CASSANDRA_KEYSPACE
              value: "vector_store"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: token
          command:
            - "conda"
            - "run"
            - "--no-capture-output"
            - "-n"
            - "rag-demo"
            - "python"
            - "-m"
            - "scripts.ingest_repos"
