apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  replicas: 1
  selector:
    matchLabels: { app: nextjs }
  template:
    metadata:
      labels: { app: nextjs }
    spec:
      containers:
        - name: nextjs
          image: rag-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: RAG_API_URL
              value: "http://rag-api:8000/rag"  # internal ClusterIP