apiVersion: v1
kind: Service
metadata:
  name: rag-worker
  labels:
    app: rag-worker
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/"
spec:
  type: ClusterIP
  selector:
    app: rag-worker
  ports:
    - name: metrics
      port: 9000
      targetPort: 9000
