apiVersion: v1
kind: Service
metadata:
  name: rag-api
  labels:
    {{- include "rag-demo.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: rag-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800