apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
  labels:
    {{- include "rag-demo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
        - name: rag-api
          image: rag-api:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: QWEN_ENDPOINT
              value: "http://qwen:8000"
          ports:
            - containerPort: 8000
              name: http