apiVersion: v1
kind: Service
metadata:
  name: rag-api
  labels:
    {{- include "rag-demo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: rag-api
  ports:
    - port: 8000
      targetPort: 8000
      name: http