[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "app"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []  # conda handles deps

[tool.setuptools.packages.find]
where = ["src"]
