# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

cassandra:
  dbUser:
    user: "cassandra"
    password: "testyMcTesterson"
    forcePassword: true
  # Increase initial timeout for schema creation with LlamaIndex
  image:
    registry: docker.io
    repository: bitnami/cassandra
    tag: 5.0.3-debian-12-r6
    pullPolicy: IfNotPresent
  auth:
    enabled: true
    username: cassandra
    password: "testyMcTesterson"
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 0.5
      memory: 2Gi
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard"
  extraEnvVars:
    - name: CASSANDRA_HEAP_NEWSIZE
      value: "128M"
    - name: CASSANDRA_MAX_HEAP_SIZE
      value: "1024M"
  startupProbe:
    # Use TCP socket check instead of exec for faster, more reliable startup detection
    enabled: true
    # Check actual CQL port which becomes available earlier than JMX
    tcpSocket:
      port: 9042
    # Don't check for exec command - let's use the TCP socket check
    exec: null
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 15  # 150 seconds (2.5 minutes) total time after initialDelay
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1
  service:
    ports:
      cql: 9042
  # Disabled completely - we'll create this separately
  initDBConfigMap: null

qwen:
  model: "Qwen/Qwen2.5-3B-Instruct"
  gpu: true
  # Increase GPU memory utilization to fit larger KV cache
  gpuMemoryUtilization: 0.85
  # Limit context window to fit available KV cache memory
  # maxModelLen: 16384
  # Limit context window to fit available KV cache memory
  maxModelLen: 11712
image:
  pullPolicy: IfNotPresent
ingestjob:
  image: rag-ingest:latest
  imagePullPolicy: Never

ragapi:
  image: rag-api:latest
  imagePullPolicy: IfNotPresent

env:
  QWEN_ENDPOINT: "http://qwen:8000"
  CASSANDRA_HOST: "rag-demo-cassandra"
  CASSANDRA_PORT: "9042"
  CASSANDRA_USERNAME: cassandra
  CASSANDRA_PASSWORD: cassandra
  CASSANDRA_KEYSPACE: vector_store
  REDIS_URL: "redis://:changeme@rag-demo-redis-master:6379/0"
  MAX_RAG_ATTEMPTS: "3"
  MIN_SOURCE_NODES: "1"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: changeme
  master:
    persistence:
      enabled: false  # fine for learning

worker:
  enabled: true
  replicas: 1
  command: ["arq", "app.worker.WorkerSettings"]


# Shared data volume for repository data and summaries
sharedData:
  # Enable persistent volume for repo data
  enabled: true
  hostPath: "/tmp/rag-demo-data"
  size: 10Gi
  mountPath: "/data"
  storageClass: "standard"

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""