# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

cassandra:
  dbUser:
    user: "cassandra"
    password: "testyMcTesterson"
    forcePassword: true
  # Increase initial timeout for schema creation with LlamaIndex
  initDBConfigMap:
    init.sh: |
      #!/bin/bash
      # Create keyspace for vector store
      echo "Creating keyspace..."
      cqlsh -u $CASSANDRA_USER -p $CASSANDRA_PASSWORD -e "CREATE KEYSPACE IF NOT EXISTS vector_store WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};"

      # Create table for vector store
      echo "Creating table..."
      cqlsh -u $CASSANDRA_USER -p $CASSANDRA_PASSWORD -e "CREATE TABLE IF NOT EXISTS vector_store.embeddings (id text PRIMARY KEY, vector_id text, content text, metadata map<text, text>, embedding blob);"

      echo "Database initialization complete."
  image:
    registry: docker.io
    repository: bitnami/cassandra
    tag: 5.0.3-debian-12-r6
    pullPolicy: IfNotPresent
  auth:
    enabled: true
    username: cassandra
    password: "testyMcTesterson"
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 0.5
      memory: 2Gi
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard"
  extraEnvVars:
    - name: CASSANDRA_HEAP_NEWSIZE
      value: "128M"
    - name: CASSANDRA_MAX_HEAP_SIZE
      value: "1024M"
  startupProbe:
    # Use TCP socket check instead of exec for faster, more reliable startup detection
    enabled: true
    # Check actual CQL port which becomes available earlier than JMX
    tcpSocket:
      port: 9042
    # Don't check for exec command - let's use the TCP socket check
    exec: null
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 15  # 150 seconds (2.5 minutes) total time after initialDelay
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1
  service:
    ports:
      cql: 9042
  # Disabled completely - we'll create this separately
  initDBConfigMap: null
  # storageClass, persistence size, etc. go here

qwen:
  model: "Qwen/Qwen3-4B-FP8"
  gpu: true
  # Reduce GPU memory utilization to accommodate 8GB GPU
  gpuMemoryUtilization: 0.75
image:
  pullPolicy: IfNotPresent
ingestjob:
  image: localhost:5000/rag-ingest:latest
  imagePullPolicy: Never

ragapi:
  image: jasonbuchanan/rag-api
  imagePullPolicy: IfNotPresent

# Shared data volume for repository data and summaries
sharedData:
  # Enable persistent volume for repo data
  enabled: true
  # Path on host machine to mount the volume
  hostPath: "/tmp/rag-demo-data"
  # Size of the persistent volume
  size: 10Gi
  # Path inside containers where volume is mounted
  mountPath: "/data"
  # Storage class for the persistent volume
  storageClass: "standard"

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""