name: tests

on:
  push:
  pull_request:

# Needed to push the generated badge back to the repo (only on main pushes)
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - name: rag_worker
            env_file: environment-worker.yaml
            env_name: worker
            path: rag_worker
          - name: rest_api
            env_file: environment-rest-api.yaml
            env_name: rag-api
            path: rest_api
          # - name: ingest
          #   env_file: environment-scripts.yml
          #   env_name: rag-demo
          #   path: ingest

    steps:
      - uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ${{ matrix.component.env_file }}
          environment-name: ${{ matrix.component.env_name }}
          cache-environment: true
          cache-downloads: true
          create-args: --yes

      - name: Install package + pytest deps
        shell: bash
        run: |
          micromamba run -n "${{ matrix.component.env_name }}" python -m pip install -e "./${{ matrix.component.path }}"
          micromamba run -n "${{ matrix.component.env_name }}" python -m pip install "pytest>=7.0" "pytest-cov>=4.0" "pytest-asyncio>=1.0.0"

      - name: Run tests with coverage (per component)
        shell: bash
        run: |
          micromamba run -n "${{ matrix.component.env_name }}" \
            pytest "./${{ matrix.component.path }}/tests" -m "not integration" \
            --cov="${{ matrix.component.path }}/src" \
            --cov-report=xml:coverage.${{ matrix.component.name }}.xml \
            --cov-report=term-missing -q

      - name: Normalize coverage data
        shell: bash
        run: |
          set -euxo pipefail
          # If parallel data files exist (from subprocess coverage), combine them into .coverage
          if ls .coverage.* 1> /dev/null 2>&1; then
            micromamba run -n "${{ matrix.component.env_name }}" python -m coverage combine || true
          fi
          test -f .coverage || { echo "ERROR: No .coverage data file found after pytest" >&2; ls -la; exit 1; }
          mv .coverage ".coverage.${{ matrix.component.name }}"

      - name: Upload coverage data + XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.component.name }}
          path: |
            .coverage.${{ matrix.component.name }}
            coverage.${{ matrix.component.name }}.xml
          if-no-files-found: error

  combine-and-badge:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4

      - name: Download all coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          merge-multiple: true

      - name: list coverage files
        shell: bash
        run: |
          echo "Coverage data files:"; ls -la .coverage* || true
          echo "Coverage XMLs:"; ls -la coverage.*.xml || true

      - name: Combine & create reports + badge
        shell: bash
        run: |
          pipx install coverage coverage-badge
          coverage combine
          coverage report -m
          coverage xml -o coverage.xml
          coverage html -d htmlcov
          mkdir -p badges
          coverage-badge -o badges/coverage.svg -f

      - name: Upload HTML coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov

      - name: Commit badge to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        shell: bash
        run: |
          if git diff --quiet badges/coverage.svg; then
            echo "No badge change."; exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add badges/coverage.svg coverage.xml
          git commit -m "chore(coverage): update badge [skip ci]"
          git push
